# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

locations = Location.create([{name: "Zebra Cafe", address: "Third Street Promenade, Santa Monica, CA", description: "The Third Street Promenade is an upscale shopping, dining and entertainment complex in the downtown area of Santa Monica, California. It is considered a premier shopping and dining district on the Westside and draws crowds from all over the Greater Los Angeles Area. Due to its proximity to the Pacific Ocean coupled with Los Angeles's mild climate, it is also a popular tourist destination.", coordinates: [-118.4976246,34.01703], resources: "None", wifi: "Good", noise: "Loud Chatter"}, 
  {name: "General Assembly", address: "1520 2nd St, Santa Monica, CA 90401", description: "At General Assembly, we are creating a global community of individuals empowered to pursue work they love, by offering full-time immersive programs, long-form courses, and classes and workshops on the most relevant skills of the 21st century – from web development and user experience design, to business fundamentals, to data science, to product management and digital marketing. Established in early 2011 as an innovative community in New York City for entrepreneurs and startup companies, General Assembly is an educational institution that transforms thinkers into creators through education in technology, business and design at nine campuses across four continents.", coordinates: [-118.4951862, 34.0129823], resources: "Snacks", wifi: "Good", noise: "Murmur"}])